create schema MovieSearch AUTHORIZATION DBA;
set schema MovieSearch;

drop table Bookmark if exists; 

create table Bookmark (
    seq integer generated by default as identity (start with 1),
    createTime bigint,
    grades varchar(5),
    openInfo varchar(10),
    thumbnail varchar(255),
    title varchar(255),
    titleLink varchar(255),
    primary key (seq)
);